apiVersion: v1
kind: Service
metadata:
  name: lamp-apache
  namespace: lamp-k8s
  labels:
    app: lamp-apache
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: lamp-apache
    tier: frontend
  type: LoadBalancer
