apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lamp-pv-claim
  labels:
    app: lamp-k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-k8s
  labels:
    app: lamp-k8s
spec:
  selector:
    matchLabels:
      app: lamp-k8s
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lamp-k8s
        tier: frontend
    spec:
      containers:
      - image: php:7.2-apache
        name: lamp-k8s
        env:
        - name: LAMP_K8S_DB_HOST
          value: lamp-k8s-mysql
        - name: LAMP_K8S_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: lamp-k8s
        volumeMounts:
        - name: lamp-k8s-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: lamp-k8s-persistent-storage
        persistentVolumeClaim:
          claimName: lamp-pv-claim
