apiVersion: v1
kind: Service
metadata:
  name: lamp-k8s-mysql
  namespace: lamp-k8s
  labels:
    app: lamp-k8s
spec:
  ports:
    - port: 3306
  selector:
    app: lamp-k8s
    tier: mysql
  clusterIP: None
