apiVersion: v1
kind: Service
metadata:
  name: lamp-php-fpm
  namespace: lamp-k8s
  labels:
    app: lamp-php-fpm
spec:
  ports:
    - port: 9000
  selector:
    app: lamp-php-fpm
    tier: backend
  type: ClusterIP
